version: '3.4'
networks:
    app-tier:
        driver: bridge
services:
    rabbitmq:
        image: 'bitnami/rabbitmq:latest'
        networks:
            - app-tier
    lorawan:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: API1/Dockerfile
        ports:
            - "5189:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
            - ASPNETCORE_URLS=http://+
        volumes:
            - ~/.aspnet/https:/https:ro
        networks:
            - app-tier
        restart: always
        depends_on:
            - "rabbitmq"